#!/bin/sh
sbatch -n 1 -c 1 --mem=8G -t 720 -o launch_hp_search_series_pratfelip_transposed_plus_clinical_l2r_f1.log --wrap="python launch_hp_search_series.py --search_config_path pratfelip_transposed_plus_clinical_l2r_f1/search_config_v0.json --job_config_path pratfelip_transposed_plus_clinical_l2r_f1/job_config_v0.json --model_config_path pratfelip_transposed_plus_clinical_l2r_f1/model_config_v0.json --num_repetitions 300 --wait_minutes 1"
sleep 10s
sbatch -n 1 -c 1 --mem=8G -t 720 -o launch_hp_search_series_pratfelip_clinical_and_deconv_l2r_f1_nopnwr.log --wrap="python launch_hp_search_series.py --search_config_path pratfelip_clinical_and_deconv_l2r_f1_nopnwr/search_config_v0.json --job_config_path pratfelip_clinical_and_deconv_l2r_f1_nopnwr/job_config_v0.json --model_config_path pratfelip_clinical_and_deconv_l2r_f1_nopnwr/model_config_v0.json --num_repetitions 300 --wait_minutes 1"
sleep 10s
sbatch -n 1 -c 1 --mem=8G -t 720 -o launch_hp_search_series_pratfelip_transposed_plus_clinical_no_stabledisease_l2r_f1_nopnwr.log --wrap="python launch_hp_search_series.py --search_config_path pratfelip_transposed_plus_clinical_no_stabledisease_l2r_f1_nopnwr/search_config_v0.json --job_config_path pratfelip_transposed_plus_clinical_no_stabledisease_l2r_f1_nopnwr/job_config_v0.json --model_config_path pratfelip_transposed_plus_clinical_no_stabledisease_l2r_f1_nopnwr/model_config_v0.json --num_repetitions 300 --wait_minutes 1"
sleep 10s
sbatch -n 1 -c 1 --mem=8G -t 720 -o launch_hp_search_series_hugolo_transposed_plus_clinical_l2r_f1_nopnwr.log --wrap="python launch_hp_search_series.py --search_config_path hugolo_transposed_plus_clinical_l2r_f1_nopnwr/search_config_v0.json --job_config_path hugolo_transposed_plus_clinical_l2r_f1_nopnwr/job_config_v0.json --model_config_path hugolo_transposed_plus_clinical_l2r_f1_nopnwr/model_config_v0.json --num_repetitions 300 --wait_minutes 1"
sleep 10s
sbatch -n 1 -c 1 --mem=8G -t 720 -o launch_hp_search_series_hugolo_clinical_and_deconv_l2r_f1_nopnwr.log --wrap="python launch_hp_search_series.py --search_config_path hugolo_clinical_and_deconv_l2r_f1_nopnwr/search_config_v0.json --job_config_path hugolo_clinical_and_deconv_l2r_f1_nopnwr/job_config_v0.json --model_config_path hugolo_clinical_and_deconv_l2r_f1_nopnwr/model_config_v0.json --num_repetitions 300 --wait_minutes 1"